services:
  epg-sync:
    image: ghcr.io/epg-sync/epg-sync:latest
    container_name: epg-sync
    restart: always
    network_mode: bridge
    ports:
      - "5690:5690"
    volumes:
      - ./config:/config
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
