server:
  host: 0.0.0.0
  port: 5690
  mode: release
  timeout: 90
  jwt_secret: "c2d4f532ab9230db9310848841c72727"
  jwt_expire_hours: 24

cache:
  type: redis
  addr: 192.168.2.130:6379
  password: ""
  db: 1
  ttl: 24h

database:
  driver: sqlite
  host: 127.0.0.1
  port: 3306
  user: root
  password: 1006
  name: /config/epg_sync.db
  debug: false
providers:
  - name: ysp
    id: ysp
    base_url: https://capi.yangshipin.cn
    enabled: true
    priority: 2
    timeout: 10s
    rate_limit: 10
    max_retries: 3
  - name: cctv.cn
    id: cctv_cn
    base_url: "https://zy.api.cntv.cn"
    enabled: true
    priority: 3
    timeout: 10s
    rate_limit: 10
    max_retries: 3
  - name: migu_tv
    id: migu_tv
    base_url: https://program-sc.miguvideo.com
    enabled: true
    priority: 4
    timeout: 10s
    rate_limit: 5
    max_retries: 2
  - name: fengshow
    id: fengshow
    base_url: https://m.fengshows.com
    enabled: true
    priority: 1
    timeout: 10s
    rate_limit: 5
    max_retries: 2
  - name: kknews
    id: kknews
    base_url: https://kapi.kankanews.com
    enabled: true
    priority: 1
    timeout: 10s
    rate_limit: 5
    max_retries: 2 
  - name: suzhou
    id: suzhou
    base_url: https://kszapi1.kan0512.com
    enabled: true
    priority: 1
    timeout: 10s
    rate_limit: 5
    max_retries: 2
  - name: jstv
    id: jstv
    base_url: https://live-lizhi.jstv.com
    enabled: true
    priority: 1
    timeout: 10s
    rate_limit: 5
    max_retries: 2
  
   

logger:
  level: info          # debug, info, warn, error
  format: console          # json, console
  output: both          # stdout, stderr, file, both
  filename: /logs/epgsync.log
  max_size: 100         # MB
  max_backups: 10
  max_age: 30          # days
  compress: false
  enable_caller: false
  enable_stack_trace: true
  stack_trace_level: error
